/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'test' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Belfry::RT-Thread Full:Board@0.1.2 */
#ifndef N32G45X
#define N32G45X 1
#endif
#ifndef N32G452
#define N32G452 1
#endif
#ifndef USE_STDPERIPH_DRIVER
#define USE_STDPERIPH_DRIVER 1
#endif
#ifndef N32_USE_RTTHREAD
#define N32_USE_RTTHREAD 1
#endif
#ifndef N32_VARIANT_xE
#define N32_VARIANT_xE 1
#endif
#ifndef SYSCLK_SRC
#define SYSCLK_SRC 2
#endif
#ifndef SYSCLK_FREQ
#define SYSCLK_FREQ 128000000
#endif
#ifndef HSE_VALUE
#define HSE_VALUE 8000000
#endif
/* Belfry::RT-Thread Full:LVGL@0.1.2 */
#define APP_USE_LVGL 1
#define LV_CONF_INCLUDE_SIMPLE 1


#endif /* PRE_INCLUDE_GLOBAL_H */
