/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'test' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "n32g45x.h"

/* Belfry::RT-Thread Full:Board@0.1.2 */
#define RTE_BELFRY_BOARD 1
/* Belfry::RT-Thread Full:GC9307C@0.1.2 */
#define RTE_BELFRY_GC9307C 1
/* Belfry::RT-Thread Full:GP21@0.1.2 */
#define RTE_BELFRY_GP21 1
/* Belfry::RT-Thread Full:Kernel@0.1.2 */
#define RTE_BELFRY_KERNEL 1
/* Belfry::RT-Thread Full:LVGL@0.1.2 */
#define RTE_BELFRY_LVGL 1


#endif /* RTE_COMPONENTS_H */
