/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'N32G452_OfficialPack_RTThread' 
 * Target:  'AC6_LVGL' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "n32g45x.h"

/* NSING::Device:N32G45x_StdPeripherals:EXTI@1.0.0 */
#define RTE_DEVICE_STDPERIPH_EXTI
/* NSING::Device:N32G45x_StdPeripherals:FLASH@1.0.0 */
#define RTE_DEVICE_STDPERIPH_FLASH
/* NSING::Device:N32G45x_StdPeripherals:GPIO@1.0.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* NSING::Device:N32G45x_StdPeripherals:MISC@1.0.0 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* NSING::Device:N32G45x_StdPeripherals:RCC@1.0.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* NSING::Device:N32G45x_StdPeripherals:SPI@1.0.0 */
#define RTE_DEVICE_STDPERIPH_SPI
/* NSING::Device:N32G45x_StdPeripherals:TIMER@1.0.0 */
#define RTE_DEVICE_STDPERIPH_TIM
/* NSING::Device:N32G45x_StdPeripherals:USART@1.0.0 */
#define RTE_DEVICE_STDPERIPH_USART


#endif /* RTE_COMPONENTS_H */
